services:
  - type: web
    name: modeva
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn modeva.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: modeva-db
          property: connectionString
